### ISSUE TITLE
Preshow music and timecode kept going

### ISSUE THREAD

**Issue by emerald-pham** [emerald-pham/WorkRepo#299]

**Comment by JoeDAlbano** [comment]
Adjustments to make on QLAB -

- Have the show track, when it goes, turn off the QLab generator. (I'd just set the "show" audio file (not the group itself) to fade and stop all in list.) This way when the show goes it turns off preshow AND the QLab timecode. Remember, once the generator goes, a 2-minute post-wait goes on it so that once the generator hits 1:02:00, it STOPS the Qlab generator and immediately goes into the show track.

**Comment by emerald-pham** [comment]
Closed today.

**Comment by emerald-pham** [comment]
Reopened. I forgot to make the main audio track fade and stop the preshow track.

**Comment by emerald-pham** [comment]
Closed today. See photo in issue for solve route.![image](https://github.com/emerald-pham/WorkRepo/assets/10377738/95eb589d-bbb8-409f-a203-e42196f0ce1d)
